version: '3'
services:
  nginx:
    container_name: shoppingfy-nginx
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3006:80'
    depends_on:
      - api
      - client

  api:
    container_name: shoppingfy-server
    build:
      dockerfile: Dockerfile.dev
      context: ./
    restart: always
    volumes:
      - /app/node_modules
      - ./package.json:/app/package.json
      - ./server:/app
    env_file:
      - ./.env
    environment:
      - PORT
      - JWT_SECRET
      - MONGO_URI
      - PAYPAL_CLIENT_ID

  client:
    container_name: shoppingfy-client
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
